import { AppShell } from "@/components/AppShell";
import { Field } from "@/components/LeadDialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, BadgeCheck, Ban, CheckCircle2, CircleAlert, ExternalLink, MailCheck, RefreshCw, SendHorizonal, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";

type ProfileForm = { legalBusinessName: string; postalAddress: string; replyToEmail: string; optOutText: string; dkimSelector: string };
const blankProfile: ProfileForm = { legalBusinessName: "", postalAddress: "", replyToEmail: "", optOutText: "Reply ‘unsubscribe’ to stop receiving outreach from us.", dkimSelector: "" };

export default function Compliance() {
  const utils = trpc.useUtils();
  const status = trpc.compliance.status.useQuery(); const suppressed = trpc.compliance.listSuppressed.useQuery();
  const [profile, setProfile] = useState<ProfileForm>(blankProfile); const [limit, setLimit] = useState(15); const [manual, setManual] = useState({ email: "", reason: "Requested no further outreach" });
  const saveProfile = trpc.compliance.saveProfile.useMutation({ onSuccess: async () => { await status.refetch(); toast.success("Commercial sender profile saved"); }, onError: error => toast.error(error.message) });
  const savePolicy = trpc.compliance.savePolicy.useMutation({ onSuccess: async () => { await status.refetch(); toast.success("Daily send limit updated"); }, onError: error => toast.error(error.message) });
  const checkDomain = trpc.compliance.checkDomain.useQuery(undefined, { enabled: false });
  const suppress = trpc.compliance.suppress.useMutation({ onSuccess: async () => { setManual({ email: "", reason: "Requested no further outreach" }); await Promise.all([suppressed.refetch(), status.refetch()]); toast.success("Recipient is now suppressed"); }, onError: error => toast.error(error.message) });
  const unsuppress = trpc.compliance.unsuppress.useMutation({ onSuccess: async () => { await Promise.all([suppressed.refetch(), status.refetch()]); toast.success("Recipient suppression removed"); }, onError: error => toast.error(error.message) });
  useEffect(() => { const current = status.data; if (!current) return; setLimit(current.quota.dailyLimit); if (current.profile) setProfile({ legalBusinessName: current.profile.legalBusinessName, postalAddress: current.profile.postalAddress, replyToEmail: current.profile.replyToEmail, optOutText: current.profile.optOutText, dkimSelector: current.profile.dkimSelector || "" }); }, [status.data]);
  const submitProfile = (event: FormEvent) => { event.preventDefault(); saveProfile.mutate(profile); };
  const submitLimit = (event: FormEvent) => { event.preventDefault(); savePolicy.mutate({ dailyLimit: limit }); };
  const submitSuppression = (event: FormEvent) => { event.preventDefault(); suppress.mutate({ email: manual.email, reason: manual.reason, source: "manual" }); };
  const health = status.data;
  return <AppShell eyebrow="SignalForge / compliance center" title="Control the conditions of sending." description="Commercial sender identity, recipient suppression, daily limits, and sender-domain checks are enforced before any approved draft can leave this workspace.">
    <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-5"><HealthCard label="SMTP transport" value={health?.smtpConfigured ? "Configured" : "Required"} ok={Boolean(health?.smtpConfigured)} detail={health?.smtpStatus ? `${health.smtpStatus.host}:${health.smtpStatus.port}` : "Mailbox connection"} icon={<MailCheck size={15} />} /><HealthCard label="Sender profile" value={health?.profile ? "Configured" : "Required"} ok={Boolean(health?.profile)} detail="Identity, address, reply-to, opt-out" icon={<BadgeCheck size={15} />} /><HealthCard label="Domain readiness" value={health?.readiness?.ready ? "Ready" : "Blocked"} ok={Boolean(health?.readiness?.ready)} detail="SPF · DKIM · DMARC" icon={<ShieldCheck size={15} />} /><HealthCard label="Send quota" value={health ? `${health.quota.remaining} left` : "—"} ok={Boolean(health?.quota.allowed)} detail={health ? `${health.quota.sentToday} of ${health.quota.dailyLimit} today` : "Daily control"} icon={<SendHorizonal size={15} />} /><HealthCard label="Suppressed" value={health?.suppressedCount ?? 0} ok={true} detail="Recipients blocked from outreach" icon={<Ban size={15} />} /></div>
    <section className="mt-6 rounded-2xl border border-[#d9e4d5] bg-[#eff6e9] p-5"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div className="flex gap-3"><CircleAlert className="mt-0.5 text-[#447447]" size={17} /><div><p className="text-xs font-bold text-[#315239]">Launch gate</p><p className="mt-1 max-w-2xl text-[11px] leading-5 text-[#637562]">Sending stays blocked until the commercial sender profile, SMTP, SPF, DKIM selector, DMARC, and daily quota all pass. Suppressed recipients are blocked at draft generation and final send.</p></div></div><Badge className={health?.sendEnabled ? "bg-[#d9edab] text-[#315639]" : "bg-[#fff0e9] text-[#a55342]"}>{health?.sendEnabled ? "Send path enabled" : "Send path protected"}</Badge></div></section>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><form onSubmit={submitProfile} className="soft-card rounded-2xl border border-[#dfe7dc] bg-white"><PanelHead icon={<MailCheck size={16} />} eyebrow="Commercial identity" title="Required sender profile" text="This footer is added to every outbound message. It is required before an approved draft can send." /><div className="grid gap-4 p-6 sm:grid-cols-2"><Field label="Legal business name *"><Input required value={profile.legalBusinessName} onChange={event => setProfile({ ...profile, legalBusinessName: event.target.value })} placeholder="Your registered business name" /></Field><Field label="Reply-to email *"><Input required type="email" value={profile.replyToEmail} onChange={event => setProfile({ ...profile, replyToEmail: event.target.value })} placeholder="hello@yourdomain.com" /></Field><Field label="Postal address *"><Textarea required className="min-h-24 resize-none" value={profile.postalAddress} onChange={event => setProfile({ ...profile, postalAddress: event.target.value })} placeholder="Business postal address" /></Field><Field label="DKIM selector *"><Input value={profile.dkimSelector} onChange={event => setProfile({ ...profile, dkimSelector: event.target.value })} placeholder="e.g. google or selector1" /></Field><Field label="Opt-out wording *"><Textarea required className="min-h-24 resize-none sm:col-span-2" value={profile.optOutText} onChange={event => setProfile({ ...profile, optOutText: event.target.value })} /></Field><div className="sm:col-span-2 flex flex-wrap justify-between gap-3"><Button type="submit" disabled={saveProfile.isPending} className="press rounded-xl bg-[#204226] text-xs font-bold text-white hover:bg-[#2b5933]">{saveProfile.isPending ? "Saving…" : "Save sender profile"}</Button><Button type="button" variant="outline" onClick={() => checkDomain.refetch()} disabled={!health?.smtpConfigured || checkDomain.isFetching} className="press rounded-xl text-xs"><RefreshCw size={13} className={checkDomain.isFetching ? "animate-spin" : ""} /> Check sender domain</Button></div>{checkDomain.data && <DomainResult data={checkDomain.data} />}</div></form>
      <div className="space-y-6"><form onSubmit={submitLimit} className="soft-card rounded-2xl border border-[#dfe7dc] bg-white"><PanelHead icon={<SlidersHorizontal size={16} />} eyebrow="Volume control" title="Daily send limit" text="Limits are enforced server-side after approval and final confirmation." /><div className="flex items-end gap-3 p-6"><Field label="Maximum sends / day"><Input required type="number" min="1" max="100" value={limit} onChange={event => setLimit(Number(event.target.value))} /></Field><Button type="submit" disabled={savePolicy.isPending} className="press h-10 rounded-xl bg-[#204226] text-xs text-white hover:bg-[#2b5933]">Save limit</Button></div></form><section className="soft-card rounded-2xl border border-[#dfe7dc] bg-white"><PanelHead icon={<AlertTriangle size={16} />} eyebrow="Operational health" title="Recent delivery status" text="Failures are retained in the outreach audit trail for review." /><div className="space-y-2 px-6 pb-6">{health?.recentFailures.length ? health.recentFailures.map(item => <div key={item.id} className="rounded-xl bg-[#fff4ef] p-3 text-[11px] text-[#8d4d40]">{item.reason}</div>) : <div className="rounded-xl bg-[#f4f8f2] p-4 text-[11px] text-[#647564]">No recent SMTP delivery failures.</div>}</div></section></div></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[.85fr_1.15fr]"><form onSubmit={submitSuppression} className="soft-card rounded-2xl border border-[#dfe7dc] bg-white"><PanelHead icon={<Ban size={16} />} eyebrow="Recipient control" title="Suppress a contact" text="Use this when a recipient opts out, is not relevant, or must never be contacted." /><div className="space-y-4 p-6"><Field label="Email address *"><Input required type="email" value={manual.email} onChange={event => setManual({ ...manual, email: event.target.value })} placeholder="contact@company.com" /></Field><Field label="Reason *"><Input required value={manual.reason} onChange={event => setManual({ ...manual, reason: event.target.value })} /></Field><Button type="submit" disabled={suppress.isPending} className="press rounded-xl bg-[#7a352d] text-xs text-white hover:bg-[#914136]"><Ban size={14} /> Block recipient</Button></div></form><section className="soft-card rounded-2xl border border-[#dfe7dc] bg-white"><PanelHead icon={<ShieldCheck size={16} />} eyebrow="Suppression list" title="Protected recipients" text="Suppressed contacts cannot receive new drafts or confirmed sends." /><div className="divide-y divide-[#edf1eb]">{suppressed.data?.length ? suppressed.data.map(item => <div key={item.id} className="flex items-center gap-3 p-4"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#fff0ed] text-[#a65343]"><Ban size={14} /></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-[#3d4f3d]">{item.email}</p><p className="mt-1 truncate text-[10px] text-[#7c8a7a]">{item.reason} · {item.source}</p></div><Button onClick={() => unsuppress.mutate({ email: item.email })} variant="outline" className="press h-8 rounded-lg px-2 text-[10px]">Remove</Button></div>) : <p className="p-6 text-xs text-[#7d8b7c]">No recipients are suppressed.</p>}</div></section></div>
    <section className="mt-6 rounded-2xl border border-[#dce7d8] bg-white p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><p className="mono text-[9px] font-bold uppercase tracking-[.16em] text-[#728271]">Public beta documents</p><p className="mt-1 text-xs text-[#718170]">Keep these pages accessible before inviting external beta users.</p></div><div className="flex flex-wrap gap-2"><Link href="/privacy"><Button variant="outline" className="press rounded-xl text-xs">Privacy <ExternalLink size={13} /></Button></Link><Link href="/terms"><Button variant="outline" className="press rounded-xl text-xs">Terms <ExternalLink size={13} /></Button></Link><Link href="/acceptable-use"><Button variant="outline" className="press rounded-xl text-xs">Acceptable use <ExternalLink size={13} /></Button></Link></div></div></section>
  </AppShell>;
}

function HealthCard({ label, value, detail, ok, icon }: { label: string; value: string | number; detail: string; ok: boolean; icon: React.ReactNode }) { return <article className="soft-card rounded-2xl border border-[#dfe7dc] bg-white p-5"><div className="flex items-center justify-between"><p className="mono text-[9px] font-bold uppercase tracking-[.14em] text-[#748174]">{label}</p><span className={"grid h-8 w-8 place-items-center rounded-lg " + (ok ? "bg-[#e8f1de] text-[#315e3a]" : "bg-[#fff0eb] text-[#ab5946]")}>{icon}</span></div><p className="display-serif mt-6 text-3xl tracking-[-.05em]">{value}</p><p className="mt-2 text-[10px] text-[#748274]">{detail}</p></article>; }
function PanelHead({ icon, eyebrow, title, text }: { icon: React.ReactNode; eyebrow: string; title: string; text: string }) { return <div className="border-b border-[#e5ece2] p-5"><div className="flex items-center gap-2 text-[#35603d]">{icon}<p className="mono text-[9px] font-bold uppercase tracking-[.16em]">{eyebrow}</p></div><h2 className="display-serif mt-2 text-2xl tracking-[-.04em]">{title}</h2><p className="mt-1 text-[11px] leading-5 text-[#758475]">{text}</p></div>; }
function DomainResult({ data }: { data: { domain: string; spfReady: boolean; dkimReady: boolean; dmarcReady: boolean; ready: boolean } }) { return <div className="sm:col-span-2 rounded-xl bg-[#f4f8f2] p-4"><p className="text-xs font-bold text-[#3b5d3c]">{data.domain} — {data.ready ? "ready" : "needs configuration"}</p><div className="mt-2 flex gap-2">{[["SPF", data.spfReady], ["DKIM", data.dkimReady], ["DMARC", data.dmarcReady]].map(([label, ready]) => <span key={String(label)} className={"rounded-full px-2 py-1 text-[9px] font-bold " + (ready ? "bg-[#dcefcf] text-[#35643d]" : "bg-[#fff0eb] text-[#a05343]")}>{String(label)} {ready ? "pass" : "missing"}</span>)}</div></div>; }
