import { AppShell } from "@/components/AppShell";
import { ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";

const documents = {
  "/privacy": { eyebrow: "SignalForge / privacy", title: "Privacy notice", intro: "This private-beta notice explains how SignalForge handles authenticated workspace data, public business discovery results, and outreach records.", sections: [["What we process", "SignalForge stores the workspace owner’s account details, saved business leads, publicly visible business contact details that the user chooses to save, outreach drafts, sender settings, suppression records, and audit activity. SMTP passwords and Telegram tokens are encrypted before storage and are not returned to the browser after saving."], ["Why we process it", "The platform processes this information to provide the user-requested discovery, lead management, outreach drafting, approval, suppression, and sender-readiness functions. Users are responsible for deciding whether a saved business contact may lawfully be contacted in their jurisdiction."], ["Retention and control", "Workspace owners can edit or delete leads and remove suppression entries through the application. Before public launch, the operator should define a formal data-retention schedule and a contact route for privacy requests."], ["Public-source data", "Discovery results originate from a public business-listing source and official business websites. SignalForge does not promise that visible email addresses are accurate, deliverable, or appropriate for marketing. The user must review each result before saving it."] ] },
  "/terms": { eyebrow: "SignalForge / terms", title: "Private beta terms", intro: "These terms describe the intended use of SignalForge during its controlled private beta.", sections: [["Permitted use", "Use SignalForge to research relevant businesses, organize your own outreach workflow, and send only messages that you have reviewed, approved, and confirmed. You must provide accurate sender identity information and respect recipient opt-outs."], ["User responsibility", "You are responsible for your prospect selection, message content, sender-domain configuration, SMTP account, direct-marketing obligations, and all messages sent from your workspace. SignalForge’s guardrails assist with control; they do not replace legal or deliverability obligations."], ["Product boundaries", "SignalForge does not scrape LinkedIn, automate LinkedIn activity, guess private email addresses, guarantee public contact data, or send messages without an explicit confirmation. The service may limit or disable sending where guardrails are incomplete."], ["Beta availability", "This is a private-beta product. Features may change as the product is improved. Do not use it for high-volume or mission-critical delivery until the operator explicitly offers a production service level."] ] },
  "/acceptable-use": { eyebrow: "SignalForge / acceptable use", title: "Acceptable use", intro: "SignalForge is designed for selective, relevant business outreach—not bulk or deceptive messaging.", sections: [["Do", "Use public business information carefully, keep records accurate, send only reviewed messages, include the required sender identity and opt-out footer, respect suppression records, and keep daily sending within the workspace limit."], ["Do not", "Do not use the service to scrape prohibited platforms, impersonate a person or business, send deceptive or harassing messages, bypass recipient opt-outs, upload unlawfully obtained contact data, distribute malware, or run bulk unsolicited campaigns."], ["Enforcement", "The operator may restrict or suspend use that threatens recipients, data sources, sender reputation, platform integrity, or legal compliance. Suppression and approval controls must not be bypassed."] ] },
};

export default function Legal() { const [location] = useLocation(); const doc = documents[location as keyof typeof documents] || documents["/privacy"]; return <AppShell eyebrow={doc.eyebrow} title={doc.title} description={doc.intro}><article className="mx-auto max-w-3xl rounded-2xl border border-[#dfe7dc] bg-white p-7 sm:p-10"><div className="flex items-center gap-2 text-[#35603d]"><ShieldCheck size={16} /><p className="mono text-[9px] font-bold uppercase tracking-[.16em]">Controlled private beta</p></div>{doc.sections.map(([title, text]) => <section key={title} className="mt-8 border-t border-[#e7ede5] pt-6 first:border-t-0 first:pt-0"><h2 className="display-serif text-2xl tracking-[-.04em]">{title}</h2><p className="mt-3 text-sm leading-7 text-[#536453]">{text}</p></section>)}</article></AppShell>; }
