import { AppShell } from "@/components/AppShell";
import { Field } from "@/components/LeadDialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { trpc } from "@/lib/trpc";
import { BellRing, EyeOff, KeyRound, LockKeyhole, Send, ShieldCheck } from "lucide-react";
import { FormEvent, useEffect, useState } from "react";
import { toast } from "sonner";

type SmtpForm = { host: string; port: number; secure: boolean; username: string; password: string; fromName: string; fromEmail: string; };
type TelegramForm = { chatId: string; botToken: string; enabled: boolean; };
const emptySmtp: SmtpForm = { host: "", port: 465, secure: true, username: "", password: "", fromName: "", fromEmail: "" };
const emptyTelegram: TelegramForm = { chatId: "", botToken: "", enabled: false };

export default function Settings() {
  const smtpStatus = trpc.smtp.status.useQuery(); const telegramStatus = trpc.telegram.status.useQuery();
  const [smtp, setSmtp] = useState<SmtpForm>(emptySmtp); const [telegram, setTelegram] = useState<TelegramForm>(emptyTelegram);
  const saveSmtp = trpc.smtp.save.useMutation({ onSuccess: async () => { setSmtp(current => ({ ...current, password: "" })); await smtpStatus.refetch(); toast.success("SMTP settings saved securely"); }, onError: error => toast.error(error.message) });
  const saveTelegram = trpc.telegram.save.useMutation({ onSuccess: async () => { setTelegram(current => ({ ...current, botToken: "" })); await telegramStatus.refetch(); toast.success("Telegram alert settings saved securely"); }, onError: error => toast.error(error.message) });
  const testTelegram = trpc.telegram.test.useMutation({ onSuccess: () => toast.success("Telegram test alert delivered"), onError: error => toast.error(error.message) });
  useEffect(() => { const settings = smtpStatus.data; if (settings?.configured) setSmtp(current => ({ ...current, host: settings.host ?? "", port: settings.port ?? 465, secure: settings.secure ?? true, username: settings.username ?? "", fromName: settings.fromName ?? "", fromEmail: settings.fromEmail ?? "" })); }, [smtpStatus.data]);
  useEffect(() => { const settings = telegramStatus.data; if (settings?.configured) setTelegram(current => ({ ...current, chatId: settings.chatId ?? "", enabled: settings.enabled, botToken: "" })); }, [telegramStatus.data]);
  const submitSmtp = (event: FormEvent) => { event.preventDefault(); saveSmtp.mutate({ ...smtp, password: smtp.password || undefined }); };
  const submitTelegram = (event: FormEvent) => { event.preventDefault(); saveTelegram.mutate({ ...telegram, botToken: telegram.botToken || undefined }); };
  return <AppShell eyebrow="SignalForge / delivery settings" title="Your mailbox. Your final say." description="SMTP makes an approved, confirmed send possible. Telegram is optional and only reports a discovery result you deliberately save.">
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]">
      <form onSubmit={submitSmtp} className="soft-card rounded-2xl border border-[#dfe7dc] bg-white"><div className="border-b border-[#e5ece2] p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f0dd] text-[#315e3a]"><KeyRound size={17} /></span><div><h2 className="display-serif text-2xl tracking-[-.04em]">SMTP connection</h2><p className="mt-1 text-[11px] text-[#778777]">Stored privately for your authenticated workspace.</p></div></div></div><div className="space-y-4 p-6"><div className="grid gap-4 sm:grid-cols-[1fr_120px]"><Field label="SMTP host *"><Input required value={smtp.host} onChange={event => setSmtp({ ...smtp, host: event.target.value })} placeholder="smtp.example.com" /></Field><Field label="Port *"><Input required type="number" min="1" max="65535" value={smtp.port} onChange={event => setSmtp({ ...smtp, port: Number(event.target.value) })} /></Field></div><Field label="SMTP username *"><Input required value={smtp.username} onChange={event => setSmtp({ ...smtp, username: event.target.value })} placeholder="you@example.com" /></Field><Field label={smtpStatus.data?.configured ? "New password (leave blank to keep current)" : "SMTP password *"}><Input type="password" required={!smtpStatus.data?.configured} value={smtp.password} onChange={event => setSmtp({ ...smtp, password: event.target.value })} placeholder={smtpStatus.data?.configured ? "••••••••" : "App password or SMTP credential"} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="From name"><Input value={smtp.fromName} onChange={event => setSmtp({ ...smtp, fromName: event.target.value })} placeholder="Your name" /></Field><Field label="From email *"><Input required type="email" value={smtp.fromEmail} onChange={event => setSmtp({ ...smtp, fromEmail: event.target.value })} placeholder="you@example.com" /></Field></div><div className="flex items-center justify-between rounded-xl bg-[#f5f8f2] p-4"><div><Label htmlFor="secure" className="text-xs font-bold text-[#3c533e]">Use TLS / secure connection</Label><p className="mt-1 text-[10px] text-[#798778]">Commonly enabled for port 465. Follow your provider’s settings.</p></div><Switch id="secure" checked={smtp.secure} onCheckedChange={secure => setSmtp({ ...smtp, secure })} /></div><Button type="submit" disabled={saveSmtp.isPending} className="press mt-2 rounded-xl bg-[#204226] text-xs font-bold text-white hover:bg-[#2b5933]">{saveSmtp.isPending ? "Encrypting & saving…" : "Save SMTP settings"}</Button></div></form>
      <aside className="space-y-5"><section className="rounded-2xl bg-[#1d3d23] p-6 text-white"><div className="flex items-center gap-2 text-[#d9edab]"><LockKeyhole size={16} /><p className="mono text-[9px] font-bold uppercase tracking-[.17em]">Credential handling</p></div><h2 className="display-serif mt-4 text-3xl leading-[1.06] tracking-[-.05em]">Encrypted before storage.</h2><p className="mt-4 text-xs leading-6 text-[#c5d2c4]">Your SMTP password and optional Telegram token are encrypted on the server. They are not returned by this app, added to exports, or shown in activity logs.</p><div className="mt-5 flex items-center gap-2 rounded-xl border border-[#456349] bg-[#243f29] p-3 text-[10px] text-[#d5e3d0]"><EyeOff size={14} /> Secrets are never displayed after saving.</div></section><section className="rounded-2xl border border-[#dce6d8] bg-[#eff6e9] p-5"><div className="flex items-center gap-2 text-[#3d7145]"><ShieldCheck size={16} /><p className="mono text-[9px] font-bold uppercase tracking-[.16em]">Dispatch safeguards</p></div><p className="mt-3 text-xs leading-6 text-[#637562]">SMTP credentials merely make manual sending possible. SignalForge sends only an approved draft after a final confirmation.</p></section></aside>
    </div>
    <section className="mt-6 soft-card rounded-2xl border border-[#dfe7dc] bg-white"><div className="border-b border-[#e5ece2] p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f0dd] text-[#315e3a]"><BellRing size={17} /></span><div><h2 className="display-serif text-2xl tracking-[-.04em]">Telegram discovery alerts</h2><p className="mt-1 text-[11px] text-[#778777]">Optional alert after you deliberately save a discovered business.</p></div></div></div><form onSubmit={submitTelegram} className="grid gap-4 p-6 lg:grid-cols-[1fr_1fr_auto]"><Field label="Telegram chat ID *"><Input required value={telegram.chatId} onChange={event => setTelegram({ ...telegram, chatId: event.target.value })} placeholder="Your personal or group chat ID" /></Field><Field label={telegramStatus.data?.configured ? "New bot token (leave blank to keep current)" : "Bot token *"}><Input required={!telegramStatus.data?.configured} type="password" value={telegram.botToken} onChange={event => setTelegram({ ...telegram, botToken: event.target.value })} placeholder={telegramStatus.data?.configured ? "••••••••" : "Token from @BotFather"} /></Field><div className="flex items-end"><Button type="submit" disabled={saveTelegram.isPending} className="press h-10 w-full rounded-xl bg-[#204226] text-xs font-bold text-white hover:bg-[#2b5933]">{saveTelegram.isPending ? "Saving…" : "Save alert settings"}</Button></div><div className="lg:col-span-2 flex items-center justify-between rounded-xl bg-[#f5f8f2] p-4"><div><Label htmlFor="telegram-enabled" className="text-xs font-bold text-[#3c533e]">Enable discovery-save alerts</Label><p className="mt-1 text-[10px] text-[#798778]">No background monitoring. An alert happens only after you press “Save lead” in Discovery.</p></div><Switch id="telegram-enabled" checked={telegram.enabled} onCheckedChange={enabled => setTelegram({ ...telegram, enabled })} /></div><div className="flex items-end"><Button type="button" onClick={() => testTelegram.mutate({ confirmation: true })} disabled={!telegramStatus.data?.configured || testTelegram.isPending} variant="outline" className="press h-10 w-full rounded-xl text-xs"><Send size={14} />{testTelegram.isPending ? "Testing…" : "Send test"}</Button></div></form></section>
  </AppShell>;
}
